pipeline {
    agent {
        label 'DevServer'
    }
    parameters {
        choice choices: ['Development', 'Production'], description: 'User to select his target node selector. ', name: 'envNodeSelector'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
            post {
                success {
                    script {
                        def jarFileName = sh(returnStdout: true, script: "find target -name '*.jar'").trim()
                        stash includes: jarFileName, name: 'MyAppJar'
                    }
                }
            }
        }
        stage('Test') {
            parallel  {
                stage('Test on DevServer') {
                    agent { label "DevServer" }
                    steps {
                        sh 'mvn test'
                    }
                    post {
                        always {
                            junit 'target/surefire-reports/*.xml'
                        }
                    }
                }
                stage('Test on PodServer') {
                    agent  { label "DevServer" }
                    steps {
                        sh 'mvn test'
                    }
                    post {
                        always {
                            junit 'target/surefire-reports/*.xml'
                        }
                    }
                }
            }
        }
        stage('Deliver') { 
            when {
                expression { return params.envNodeSelector == 'Development' }
            }
            agent { label 'DevServer' }
            steps {
                script {
                    
                    dir ('/home/ubuntu/deployment') {
                        unstash 'MyAppJar'
                        def jarFileName = sh(returnStdout: true, script: "find /home/ubuntu/deployment -name '*.jar'").trim()
                        sh "jar -xvf ${jarFileName}"
                        sh "java -jar ${jarFileName}" //to execute the jar file
                    }
                    
                }
            }
        }
    }
}